### ISSUE TITLE
Commit 1b474bf compiles with CUDA 10.2, but not CUDA 9.1 or 8

### ISSUE THREAD

**Issue by TonkomoLLC** [Atizar/RapidCFD-dev#68]
Hello,

Maybe this does not matter if the intention is to support newer CUDA versions.

Ubuntu 18.04 + CUDA 9.1 + RapidCFD commit 1b474bf does not compile.  The following error is generated during compiling:

```
SOURCE=UOPwrite.C ;  nvcc -Xptxas -dlcm=cg -std=c++11 -m64 -arch=sm_35 -Dlinux64 -DWM_DP -Xcompiler -Wall -Xcompiler -Wextra -Xcompiler -Wno-unused-parameter -Xcompiler -Wno-vla -Xcudafe "--diag_suppress=null_reference" -Xcudafe "--diag_suppress=subscript_out_of_range" -Xcudafe "--diag_suppress=extra_semicolon" -Xcudafe "--diag_suppress=partial_override" -Xcudafe "--diag_suppress=implicit_return_from_non_void_function" -Xcudafe "--diag_suppress=virtual_function_decl_hidden" -O3  -DNoRepository -D__RESTRICT__='__restrict__' -DOMPI_SKIP_MPICXX -I/opt/ThirdParty-dev/platforms/linux64Nvcc/openmpi-2.1.1/include -IlnInclude -I. -I/opt/RapidCFD-dev/src/OpenFOAM/lnInclude -I/opt/RapidCFD-dev/src/OSspecific/POSIX/lnInclude   -Xcompiler -fPIC -x cu -D__HOST____DEVICE__='__host__ __device__' -o Make/linux64NvccDPOptOPENMPI/UOPwrite.o -c $SOURCE
/opt/RapidCFD-dev/src/OpenFOAM/lnInclude/DeviceConfig.H:66:50: error: specialization of ‘template<class T> bool Foam::hasAtomicAdd()’ in different namespace [-fpermissive]
 inline bool Foam::hasAtomicAdd<int>()
                                                  ^
/opt/RapidCFD-dev/src/OpenFOAM/lnInclude/DeviceConfig.H:56:32: error:   from definition of ‘template<class T> bool Foam::hasAtomicAdd()’ [-fpermissive]
     template<class T>
                                ^           
/opt/RapidCFD-dev/src/OpenFOAM/lnInclude/DeviceConfig.H:72:51: error: specialization of ‘template<class T> bool Foam::hasAtomicAdd()’ in different namespace [-fpermissive]
 inline bool Foam::hasAtomicAdd<long>()
                                                   ^
/opt/RapidCFD-dev/src/OpenFOAM/lnInclude/DeviceConfig.H:56:32: error:   from definition of ‘template<class T> bool Foam::hasAtomicAdd()’ [-fpermissive]
     template<class T>
                                ^           
/opt/RapidCFD-dev/src/OpenFOAM/lnInclude/DeviceConfig.H:78:52: error: specialization of ‘template<class T> bool Foam::hasAtomicAdd()’ in different namespace [-fpermissive]
 inline bool Foam::hasAtomicAdd<float>()
                                                    ^
/opt/RapidCFD-dev/src/OpenFOAM/lnInclude/DeviceConfig.H:56:32: error:   from definition of ‘template<class T> bool Foam::hasAtomicAdd()’ [-fpermissive]
     template<class T>
                                ^           
/opt/RapidCFD-dev/src/OpenFOAM/lnInclude/DeviceConfig.H:84:53: error: specialization of ‘template<class T> bool Foam::hasAtomicAdd()’ in different namespace [-fpermissive]
 inline bool Foam::hasAtomicAdd<double>()
                                                     ^
/opt/RapidCFD-dev/src/OpenFOAM/lnInclude/DeviceConfig.H:56:32: error:   from definition of ‘template<class T> bool Foam::hasAtomicAdd()’ [-fpermissive]
     template<class T>
```

Removing CUDA 9.1, rebooting, installing CUDA 10.2, and then compiling from a fresh (wclean'd) RapidCFD and ThirdParty setup works.

If the intention is to only support newer CUDA versions, then the README instructions should be updated. 

If the intention is to continue support of older CUDA versions, then please be aware that something is not working on at least my machine with older CUDA versions. I do not have a fix yet.

Best,

Eric

**Comment by daniel-jasinski** [comment]
Hello,

Thank you for this info. 
I did not have the opportunity to check older CUDA versions and therefore did not catch this one.
The intention is to maintain support for older CUDA.
I will prepare a fix for older versions, but at the moment I am working on something else.
If you want, the fix should be easy, you should just put the template specializations defined in _DeviceConfig.H_
into the **Foam** namespace instead of the global namespace.

Thanks,
Daniel

**Comment by TonkomoLLC** [comment]
Thanks, Daniel, for the quick reply.  For sure, you are correct on the solution.
I attempted to do as you suggested. A pull request has been generated.

Please see #69

Presently I can compile with CUDA 8.

Best regards,

Eric
