### ISSUE TITLE
atomicAdd compilation error

### ISSUE THREAD

**Issue by TonkomoLLC** [Atizar/RapidCFD-dev#70]
Hello,

I am writing about commit afe3dd601be9a784b3b4dfd033d89a24b0538c59.

When compiling with CUDA 10.2, I get the following error: 

```
matrices/lduMatrix/solvers/GAMG/GAMGSolverAgglomerateMatrixF.H(260): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (Foam::scalar *, float)
          detected during instantiation of "void Foam::GAMG::asymAtomicAgglomerate::impl(T *, T *, T *, const T *, const T *, const Foam::label &) [with T=float]" 
(278): here

1 error detected in the compilation of "/tmp/tmpxft_00005a89_00000000-6_GAMGSolverAgglomerateMatrix.cpp1.ii".
```

Maybe this is not your preferred solution, but I can get the program to compile and run with changing line 260 as follows:

```
            atomicAdd(reinterpret_cast<float*>(coarseDiag + cell), fu + fl);
```

For your consideration.

Cheers,
Eric

**Comment by daniel-jasinski** [comment]
Hello,

Thank you for the report.
Could you check if it compiles when you change the mentioned line 260 to this:
```
atomicAdd(cDiag + cell, fu + fl);
```
Thanks,
Daniel

**Comment by TonkomoLLC** [comment]
Thanks, Daniel, for the suggestion. I confirm that your proposed code, replacing coarseDiag with cDiag at the referenced line 260, compiles without error on CUDA 8 an CUDA 10.2.

Cheers,

Eric

**Comment by daniel-jasinski** [comment]
Thanks, Eric, I added a commit fixing this and another similar error.
I would be grateful for your feedback.

Daniel

**Comment by TonkomoLLC** [comment]
Hi, Daniel. Thanks for all of the improvements you are making to RapidCFD.

I tested compiling commit a19e8cff470bf07b1298697b9c478d958e6eb285 with CUDA 8 and CUDA 10.2. I can compile successfully with both versions of CUDA,, and I am also able to run a test case using the GAMG solver. 

I think your latest changes are working, based on these preliminary tests.

Best regards,
Eric

**Comment by daniel-jasinski** [comment]
Hi, Eric. I am glad you enjoy using RapidCFD.

I just made some changes to further improve speed and also build time.
These are quite big changes so I might not have caught every issue during my tests.
Therefore I would be happy for more of your great feedback.

Thanks,
Daniel

**Comment by TonkomoLLC** [comment]
Hi, Daniel. Indeed, I have been really impressed by your work on RapidCFD and I am very appreciative of all the new changes you have been implementing recently.  I am glad my feedback is helpful.

I am presently compiling commit 06e8c1167505c7c9a6eae4788ea1d9aabd405837.  On CUDA 10.2 with gcc 7.4.0, this is working well. I'll do some basic tests when compilation is done. 

However, there is a choice needed on the flag ‘-Wimplicit-fallthrough=0’.  gcc supports this flag after I think gcc 7.  I am not sure of the exact version. Nonetheless, older version of CUDA do not support such recent gcc versions.  For example, CUDA 8 supports only up to gcc 5, but gcc 5 does not support the -Wimplicit-fallthrough flag.  Thus I think there is a choice: 

- remove the -Wimplicit-fallthrough flag to keep compatibility with older CUDA versions without requiring the user to make changes to the c++ rules file before compiling.

or

- update the readme to instruct the user to remove the referenced flag before compiling.

I tried upgrading to gcc version 7 on this machine, and that's how I discovered gcc 7 does not work with CUDA 8. I have reverted back to gcc-5.5 but now I get new errors like:

```
/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9220): error: argument of type "const void *" is incompatible with parameter of type "const float *"
```
I am not sure - I think this may be related to a problem with my gcc installation after reverting to gcc 5.  I will try to fix this and then resume testing with CUDA 8.  However, my notes above on the gcc flag  -Wimplict-fallthrough are valid and for your consideration of how to support older CUDA versions.

Best regards,

Eric

**Comment by daniel-jasinski** [comment]
Hi Eric,

Regarding the flag, considering the two options I would prefer to remove the flag.
I only added it because my compiler generated a lot of annoying warnings.
Older compilers most likely are not as pedantic.

If you create a commit removing the flag I will merge it.

Thanks,
Daniel

**Comment by TonkomoLLC** [comment]
Hi, Daniel,

Thanks for the feedback.  I will for sure make pull request as soon as I finish compiling.  Please note that I also had to remove the `-Xcompiler` flag to compile with CUDA 8 + gcc 4.9.

The gcc error I reported above related to avx512 is due to CUDA 8 not being compatible with gcc 5.5.  I considered my options for downgrading gcc 5.5 to gcc 5.4 and just installing gcc 4.9, and I decided I had less risk of messing up my computer by just installing gcc 4.9 alongside gcc 5.5 and gcc 7.4.  Therefore, right now I am recompiling RapidCFD with CUDA 8 + gcc 4.9 on this particular machine.

The CUDA 10.2 machines are still compiling as I write this note.

As an aside, do you notice that as compared to commit f3775ac96129bfee68655e11e63ff5d62bccb4b9, some change recently causes RapidCFD to use more GPU memory on a case?

I will try to document this further as soon as possible. There were a number of changes recently and unfortunately I could not run large cases after each commit, so I am unsure where the change in memory usage appeared.

Thanks,

Eric

**Comment by TonkomoLLC** [comment]
Hi, Daniel -
I am continuing to test.

Compilation now complete with one of my CUDA 10.2 machines. libdynamicMesh is now gone. Should the dynamicMesh solvers (i.e., pimpleDymFoam, rhoPimpleDyMFoam, sonicDyMFoam, and interDyMFoam) be removed, too, to avoid compilation errors?  

Thanks,
Eric

**Comment by daniel-jasinski** [comment]
Hi Eric,

I moved the code from libdynamicMesh to libdynamicFvMesh, because the former had only one useful class remaining in it.
I updated options files for the dynamic mesh solvers so they should build without errors.
Unless I forgot about something, then we should fix that rather than removing the solvers.

Thanks,
Daniel

**Comment by TonkomoLLC** [comment]
Hi, Daniel,

The libdynamicMesh report was my error. I wclean'd the installation and everything compiled OK.  I confirm that interDyMFoam works.  Sorry about that incorrect error report.

commit 7898e05560525bc94676a31eb7e8e7fffce055f2 compiles with CUDA  8 and 10.2.  CUDA 10.2 passes some basic tests (small tutorial cases):
- cavity with interFoam
- pitzDaly with rhoPimpleFoam
- sloshingTank3D with interDyMFoam

I'll check out CUDA 8 and some larger cases (see if I can substantiate my recollection that more memory is used now - hopefully I am mistaken) and get back to you as soon as possible.  However, with commit 7898e05560525bc94676a31eb7e8e7fffce055f2, so far so good.

Thanks for all of your work on this valuable project.

Best regards,

Eric

**Comment by daniel-jasinski** [comment]
Hi Eric, 

Thank you again for your great report.
I think I managed to fix the compilation errors with CUDA 8.
I would be grateful if you could verify it.

Regarding memory usage.
The purpose of the commit that caused the issue was to reduce memory allocations during complex reduce operations.
I know that thrust behind the scenes performs some temporary allocations so maybe that is the issue.
Either way, it would be good to know if the problem still persists with the latest changes.

Thanks again,
Daniel

**Comment by TonkomoLLC** [comment]
Dear Daniel,

Amazing. I didn't get a chance to try to fix the CUDA 8 errors, and you've already posted a solution. 

I am happy to report commit 915b9f0837893d5009d39e5d41b50727a169062e compiles with both CUDA 8 and CUDA 10.  

I am also happy to report that commit 915b9f0837893d5009d39e5d41b50727a169062e solves the memory problem with CUDA 8 for the referenced 1.27 million cell test case (I tried both K20 and GTX-1050Ti GPU's with CUDA 8 + commit 915b9f0837893d5009d39e5d41b50727a169062e).

I'll do some additional testing, but so far this appears to be working really well. Thank you for providing these fixes!

Best regards,

Eric

**Comment by daniel-jasinski** [comment]
Hi Eric,

Thank you again for the report.
It is good to see that the errors are fixed.

Regarding the improvements in speed.
I corrected a few small "performance bugs" that should give maybe a few percents of speedup.
The biggest improvement was for parallel runs using GAMG, thanks to moving the coarsest matrix to the CPU and solving it directly. This helped to avoid launching a large number of very small kernels and reduced MPI calls.
For the moment I do not see much more room for improvement without finding some new algorithms for parallel smoothers and preconditioners.

Thanks,
Daniel

**Comment by TonkomoLLC** [comment]
Dear Daniel,

Thanks for the great feedback on speed. When I did further testing yesterday I also noticed a "few percentage points" of speedup but I did not check parallel usage of GAMG (I used a single GPU for my testing of commit 915b9f0 so far). I'll keep this in mind as I continue to work with RapidCFD.

Again, thanks so much for all these improvements. 

Best regards,

Eric

**Comment by daniel-jasinski** [comment]
Dear Eric,

I am glad that you find this project useful and thank you for your help.

I started adding support for Clang as an alternative to Nvcc.
After some modifications, I was able to build RC with Clang 9.0.0.
Clang does not support CUDA 10 so I had to use CUDA 8.0.
Some minor changes to the Thrust sources were also required.
If you are interested you can try that out.

Best regards,
Daniel

**Comment by TonkomoLLC** [comment]
Dear Daniel,

Thanks so much for these updates to RapidCFD, and for getting in touch with me about testing.

I should have written to you since my preliminary testing is already finished. Earlier today I updated, compiled, and did some preliminary tests with commit 3043cafa8f403c6744aa0e9a15f0904f9a9e1c2c.
- I successfully compiled this latest commit with CUDA 8 and CUDA 10.2 using Nvcc.  
- Preliminary testing went well, and since openmpi was upgraded to 4.0.2, I also checked a parallel run with 2x K20's on two separate machines over TCP/IP. Everything was fine, even the memory usage with CUDA 8.

However, I did not test Clang 9.0.0.  I'll try to get to this with CUDA 8.  Personally I have not yet used Clang as an alternative to Nvcc. 

Thanks again, and best regards,

Eric

**Comment by TonkomoLLC** [comment]
Hi, Daniel,

I have not been able to resolve my Clang compile issues with CUDA 8.  As you noted, Clang 9.0.0 is not compatible with CUDA 10.2, which I am now using on most of my GPU capable machines (CUDA 8 on the other).  

Were you able to successfully compile RapidCFD using Clang 9.0.0 and CUDA 8?  

Thanks,

Eric

**Comment by daniel-jasinski** [comment]
Hi Eric,

I was able to build with Clang but it required a little bit of hacking.
On Linux Nvcc is fine and using Clang is more of a curiosity.
I did it just because I am thinking of porting RC to Windows.
The problem on Windows is that Nvcc only supports Microsoft Visuall C++ as the host compiler, but MSVC is unable to build OF or RC. So my idea was to use Clang on Windows, and porting to Clang on Linux was just an intermediate step, but it helped me catch a few subtle bugs.

To actually make the Linux build:
- Add missing **libdevice** libraries to CUDA _nvvm/libdevice_ directory (I actually copied them from Windows CUDA installation)
- Overwrite the default CUDA 8.0 Thrust with the latest one from CUDA 10.2. You can do that by setting **THRUST_HOME** env variable before sourcing _etc/bashrc_. Details are [here](https://github.com/Atizar/RapidCFD-dev/blob/master/etc/config/settings.sh#L350).
- Do some modifications to thrust code to resolve Clang compatibility issues and annoying warnings.

As you see it is a little bit of hassle and I don't know if it is worth the effort, so for now, I think of it as a "shadow support for Clang" ;) 

I reported the issues I had with Thrust, so with a little bit of luck in the future, the build process will be smoother.

Thanks,
Daniel

**Comment by TonkomoLLC** [comment]
Hi, Daniel,

I appreciate the background.  Now I understand why you wish to add Clang support.

Thanks so much for these instructions. I was wondering about CUDA 8 Thrust compatibility with Clang 9.0.0.  Good tip on using Thrust from CUDA 10.2.

When I can, I'll try the approach you took and I see if I can replicate your success with modifying Thrust to resolve Clang compatibility issues and annoying warnings.  I almost exclusively use Linux so like you say, for me it is a curiosity and learning opportunity. 

I just noticed you posted an issue to thrust's GitHub site regarding compilation of code with thrust compiled with Clang on Windows.  Hopefully you are able to get help here.

As always, I am grateful for your continued support or RC. 

Best regards,

Eric
